### ISSUE TITLE
Fix function `cleanedTrails` in `Table.vue`

### ISSUE THREAD

**Issue by andreas-groos** [NCJS/nc-trails#3]
Currently it combines different 'sections' of the trail but it fails sometimes and you have multiple trails called the same ('Pioneer Trail' etc).

Find out why and fix it.

Bonus: Create an external `utils.js` file and export that function from there.

**Comment by shlomitbitton** [comment]
Hi Andreas,
I am thinking  about having a Set instead of [], to eliminate duplicate. What do you think?
If yes I am not sure how to implement it.

**Comment by andreas-groos** [comment]
I assume with Set you mean Object? That was my solution: 
-Create a trail object.
- Iterate though the trail array, check if trail object already has the property of the trail name
  - if yes, add the current trail to existing trail (add length, add the trail geometry)
  - if no create that property with the info of the current trail

Turn the trail object again into a array and pass it to the <Map> and <Table>

Good thought, curious to see your implementation.

**Comment by andreas-groos** [comment]
You will want to use 'computed properties', see [here](https://tylermcginnis.com/computed-property-names/).

Write me on Slack next time, otherwise I might not see it for a while

**Comment by shlomitbitton** [comment]
How do we handle issues that had been committed?

**Comment by andreas-groos** [comment]
That should explain the flow. https://guides.github.com/introduction/flow/.

**Comment by shlomitbitton** [comment]
Andreas, I realized I missed the bonus part. Shall we create a separate ticket for that?
