### ISSUE TITLE
Create an `/about` page

### ISSUE THREAD

**Issue by andreas-groos** [NCJS/nc-trails#8]
Set up a super simple router and create an `/about` page.

**Comment by andreas-groos** [comment]
https://router.vuejs.org/guide/#javascript

**Comment by andreas-groos** [comment]
Couple of issues:

- if I just load `localhost:8080` nothing is visible, I have to go `localhost:8080/Home` for the root page to show, please fix this in `main.js`
- There is an uneccesary <Header> component in `Home.vue`, you already have it in `App.vue` which is the 'right' place for it to be as it then doesn't have to be included in every individual page.
- Can we have an external link to the github repo in the <Header>?
- The 'Loading' component hides the <Header>, can we make some space for the <Header> to show while 'loading', seems like better UX.

**Comment by shlomitbitton** [comment]
Your last two comments were not very clear to me, I think a word is missing in each one...

- Can we have an external link to the github repo in the ?
- The 'Loading' component hides the , can we make some space for the to show while 'loading', seems like better UX.

I made the other changes.

**Comment by andreas-groos** [comment]
Got merged, is closed
